import { Html, Head, Main, NextScript } from "next/document";
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Document({children}) {
  return (
    <Html lang="en">
      <Head />
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}

/* import { Html, Head, Main, NextScript } from "next/document";
import { dir } from "i18next";
import { languages } from "@/components/i18n/settings";


export const metadata = {
  title: "Aleksandra Cislowski Städfirma",
  description: "Cleaning services in Stockholm",
};

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export default function RootLayout({params: { lng } }) {
  return (
    <Html lang={lng} dir={dir(lng)}>
      <Head />
      <body>
        <Navigation lng={lng} />
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
*/